AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9
  Sample SAM Template for flask

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    
Resources:
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.create_case
      Runtime: python3.9
      Events:
         ApiEvent:
           Type: HttpApi
           Properties:
            Path: /create
            Method: POST

  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.get_case
      Runtime: python3.9
      Events:
         ApiEvent:
           Type: HttpApi
           Properties:
            Path: /case/{case_id}
            Method: GET

Outputs:
  Endpoint:
    Description: "API Gateway endpoint URL for Prod stage for the endpoint"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"

